// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which half of the app the user is running. Chosen during onboarding and
 * switchable later; it decides which dependencies are required and which
 * screens are reachable.
 */
export type AppMode = "host" | "guest";
