// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";

export type AppSettings = { 
/**
 * `None` until onboarding completes.
 */
mode: AppMode | null, port: number, room: string, nickname: string, 
/**
 * BCP-47 tag; the UI ships `tr` and `en`.
 */
language: string, 
/**
 * Whether the host attaches a hidden client to read live room state.
 * Disabling it trades the rich panel for one fewer name in the user list.
 */
monitorEnabled: boolean, discordEnabled: boolean, };
