// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightReport } from "./PreflightReport";
import type { SessionState } from "./SessionState";
import type { TailnetStatus } from "./TailnetStatus";

export type DiagnosticsReport = { appVersion: string, operatingSystem: string, dependencies: PreflightReport, tailnet: TailnetStatus | null, 
/**
 * Kept separate from `tailnet`: a missing CLI and a stopped daemon both
 * need an explanation, but neither should make the whole report fail.
 */
tailnetError: string | null, session: SessionState, };
