// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Invite } from "./Invite";
import type { ServerState } from "./ServerState";

/**
 * Everything the host screen needs once a party is live.
 */
export type HostingInfo = { invite: Invite, inviteCode: string, deepLink: string, 
/**
 * This machine's own tailnet address — the one the server is bound to.
 *
 * Not decoration: it is the address the host's own Syncplay has to use.
 * `invite.host` may be a masqueraded address that only resolves inside
 * the tailnet this node was shared into, which does not include here.
 */
tailscaleAddress: string, server: ServerState, monitorAttached: boolean, };
