// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Invite } from "./Invite";
import type { ServerState } from "./ServerState";

/**
 * Everything the host screen needs once a party is live.
 */
export type HostingInfo = { invite: Invite, inviteCode: string, deepLink: string, 
/**
 * This machine's own tailnet address, shown for troubleshooting. May
 * differ from `invite.host` when the node is shared into another tailnet.
 */
tailscaleAddress: string, server: ServerState, monitorAttached: boolean, };
