// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A party, in the form a guest receives it.
 */
export type Invite = { 
/**
 * Tailscale address or MagicDNS name of the host.
 */
host: string, port: number, password: string, room: string, };
