// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A party, in the form a guest receives it.
 */
export type Invite = { 
/**
 * The address most guests should use.
 */
host: string, 
/**
 * Other addresses that reach the same server.
 *
 * No single address suits everyone. A node shared into somebody else's
 * tailnet is reached on a masqueraded address that means nothing anywhere
 * else — including on the host's own machine — while peers inside the
 * host's tailnet need its real address or MagicDNS name. Carrying every
 * candidate lets the joining side find out which one actually answers
 * instead of the host having to know who is on which tailnet.
 */
alternateHosts: Array<string>, port: number, password: string, room: string, };
