// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who is behind a Tailscale IP.
 */
export type PeerIdentity = { displayName: string, loginName: string | null, hostname: string | null, };
