// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { PreflightItem } from "./PreflightItem";

/**
 * Snapshot of every dependency relevant to the chosen mode.
 */
export type PreflightReport = { mode: AppMode, items: Array<PreflightItem>, };
