// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomView } from "./RoomView";

/**
 * What the room panel renders.
 */
export type RoomSnapshot = { connected: boolean, rooms: Array<RoomView>, };
