// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatcherView } from "./WatcherView";

export type RoomView = { name: string, watchers: Array<WatcherView>, 
/**
 * False when two people have different files open — the single most
 * common reason a movie night desyncs, and something the server already
 * knows but no Syncplay UI puts in front of the host.
 */
everyoneOnTheSameFile: boolean, };
