// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCompatibility } from "./FileCompatibility";
import type { WatcherView } from "./WatcherView";

export type RoomView = { name: string, watchers: Array<WatcherView>, 
/**
 * Backward-compatible summary for older clients. False only when the
 * files are known to be incompatible; a room still loading is not
 * reported as a mismatch.
 */
everyoneOnTheSameFile: boolean, 
/**
 * A more useful compatibility signal than filenames alone. Different
 * releases of the same film often have different names, while their
 * durations still reveal that they are suitable for synchronized play.
 */
fileCompatibility: FileCompatibility, };
