// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostingInfo } from "./HostingInfo";
import type { StartupStep } from "./StartupStep";

/**
 * Where the host is in the start-up sequence.
 */
export type SessionState = { "phase": "idle" } | { "phase": "starting", step: StartupStep, } | { "phase": "hosting" } & HostingInfo | { "phase": "failed", message: string, };
