// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";

/**
 * A partial settings update. Absent fields are left alone, so the UI can send
 * just the toggle the user touched.
 */
export type SettingsPatch = { mode: AppMode | null, port: number | null, room: string | null, nickname: string | null, language: string | null, monitorEnabled: boolean | null, discordEnabled: boolean | null, };
