// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the daemon reports about this node.
 */
export type TailnetStatus = { 
/**
 * `Running`, `Stopped`, `NeedsLogin`, and so on, straight from the daemon.
 */
backendState: string, ipv4: string | null, 
/**
 * MagicDNS name with the trailing dot stripped.
 */
dnsName: string | null, isRunning: boolean, };
